# Generated by Django 5.0.6 on 2024-05-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='surveys/'),
        ),
    ]
