# Generated by Django 5.0.6 on 2024-05-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_survey_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=models.ImageField(default='', upload_to='surveys/'),
        ),
    ]
