# Generated by Django 5.0.6 on 2024-05-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_survey_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='survey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.survey'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='total_points',
            field=models.FloatField(default=0),
        ),
    ]
